### ISSUE TITLE
Using Amazon Pay along side Recurly.js

### ISSUE THREAD

**Issue by nevinlaughlin** [recurly/pay-with-amazon#10]
I'm self hosting a recurly payment form with both "pay-with-amazon" and recurly.js v4. When I try to  pay with amazon recurly is requiring the credit card fields: cc number, exp. month and year. I'm using radio input fields to switch between card and amazon, and even though amazon is checked I still get the credit card validation errors. I'm not sure what I'm missing or need to do ?

Thanks!

**Comment by chrissrogers** [comment]
@nevinlaughlin it sounds like when you're submitting the form, Recurly.js is trying to generate a token from the credit card form. That isn't necessary when using pay-with-amazon, so be sure to check your form handler, and ensure it doesn't attempt to tokenize when checking out with amazon. Hope that helps!

**Comment by nevinlaughlin** [comment]
Thanks, that makes sense.

This tells me that the payment is ready to be submitted, right?
` id: 'abc-xyz', // Amazon billing agreement id.
  consent: true // Whether billing consent has been given`

Do I get a response once the form is submitted to know it was successful?

**Comment by chrissrogers** [comment]
Yes, once you have consent, the billing agreement id can be used to make payments, create subscriptions, etc.

Since the amazon customer flow is entirely within the checkout page, you won't have a form submission as part of the process to create a billing agreement. Once you have it, it's typical to submit the billing agreement to your backend server for usage in the Recurly API.

**Comment by nevinlaughlin** [comment]
Thanks, again!

One more question, if i'm going to use recurly's api on a backend server to create the subscription and account, what info does amazon pay send to recurly so I can associate the recurly account and subscription? Are they sending the Amazon billing agreement id or Name, address etc...

**Comment by chrissrogers** [comment]
The association is based on the billing agreement id, but that isn't sent to Recurly from Amazon -- that just needs to be sent in with your API request. We then retrieve all customer information from Amazon. You can think of it as essentially a credit card number that Amazon controls.

**Comment by chrissrogers** [comment]
In Recurly, the subscription and account must be associated via an API call. The best way is to create the account when you're creating the subscription. You can read more about that call here: https://dev.recurly.com/docs/create-subscription

**Comment by chrissrogers** [comment]
I'm going to close this just for record-keeping purposes, but feel free to drop any other questions you have about the `pay-with-amazon` library here.

**Comment by nevinlaughlin** [comment]
Thanks! You've been very helpful.

When creating the subscription, I'm passing the Amazon billing agreement id (ex. $billing_info->amazon_billing_agreement_id) instead of the recurly-token.

This is also helpful, https://dev.recurly.com/docs/create-an-accounts-billing-info-using-external-token.
