### ISSUE TITLE
_this.getAssetPath is not a function

### ISSUE THREAD

**Issue by pavelivanov** [recurly/pay-with-amazon#20]
Hi there,

I tried to use Release 2.0.0 and got error: **_this.getAssetPath is not a function**. Didn't find **getAssetPath** in PayWithAmazon methods. Was looking for an issue in this repo and found only https://github.com/recurly/pay-with-amazon/pull/12 where this method discussed. Looks like smth went wrong within 2.0.0:

<img width="400" src="https://user-images.githubusercontent.com/966176/87317119-40d42080-c52f-11ea-8e93-352f6b2e63c0.png" />

**Comment by chrissrogers** [comment]
Thanks for reporting this! We have a fix on the way.
