### ISSUE TITLE
Can't render small button

### ISSUE THREAD

**Issue by SuperStromboli** [recurly/pay-with-amazon#5]
The button options are a little confusing after having been wrapped around the native Amazon button options, but with the button configuration below I would expect to get a small button (72x30) that is gold and only says "Pay" with the "a" logo.  Translating back to the Amazon API, _Size_ becomes _type_ and _type_ becomes _kind_.

`{ id: 'pay-with-amazon', type: 'small', color: 'Gold', kind: 'pay' }`

The output is correct except that the size is medium (90x45).

**Comment by chrissrogers** [comment]
It looks like Amazon has added additional button parameters for size that were not present at our last release. We don't explicitly support size as Amazon defines it now, but instead an interpretation that mirrors the 'Pay with Amazon' and 'Pay' buttons in medium. We should add this, so I'll consider it a feature req. We welcome contribs and I would be more than happy to review any change :)

**Comment by SuperStromboli** [comment]
Thanks for the info.  I can get by with a CSS override for the time being
so it's not a huge deal.

**Comment by phlemoine** [comment]
I am curious to understand how the "kind" parameter can be used. I want to change the default button when using the "HostedPayment" type. See question at https://sellercentral.amazon.com/forums/message.jspa?messageID=3871348#3871348. If any one reading here can help, that'd be greatly appreciated.

**Comment by judith** [comment]
@phlemoine the `kind` option values should be 'pay' or 'login' to specify which kind of Amazon button to render depending on whether or not the user is already authenticated through Amazon.

It is used as part of the following code in conjunction with the `type` option to determine if the button should say `Login` or `Login with Amazon` or `Pay` or `Pay with Amazon`:

```
  if (opts.button.kind === 'login') {
    opts.button.type = opts.button.type === 'small' ? 'Login' : 'LwA';
  } else {
    opts.button.type = opts.button.type === 'small' ? 'Pay' : 'PwA';
  }
```

I don't believe that we currently support 'HostedPayment' as a `type` setting, but as @chrissrogers said we welcome contributions and would be more than happy to review any changes to support that button type.

**Comment by phlemoine** [comment]
I've been working with Amazon support team, and they confirmed that hostedPayments type only allows the PayWithAmazon button. The A button and the Pay buttons cannot be used when the type is hostedPayment
