### ISSUE TITLE
Using with AngularJS

### ISSUE THREAD

**Issue by SimplyWonder** [recurly/pay-with-amazon#6]
Hi, can I use pay-with-amazon in my angular application? Meaning, have the pay-with-amazon.js included in the head tag but have the element such as `<div id="pay-with-amazon"><div>` in a different state? 

Right now when I do that, I'm getting `Uncaught TypeError: Cannot read property 'getElementsByTagName' of null`. 

Thank you.

**Comment by chrissrogers** [comment]
Unfortunately I don't think this will be possible by the way the Amazon libraries are designed. They require that they both be loaded in the document head and that the target element be available on document ready. It's an unfortunate limitation on Amazon's side.
