### ISSUE TITLE
After Login  address book and method showing but purchase link not working

### ISSUE THREAD

**Issue by alok12** [recurly/pay-with-amazon#9]
Hello,

I want to know that when i will click on the pay with amazon link login window open after login thers is method and address book will be shown but "Pay" button not came so how to i know payment done and completed and how to get the unique id after complete payment ? Please help me.

Thanks

**Comment by chrissrogers** [comment]
You should listen to the 'change' event and check for presence of the `id` property. Once the customer selects an address from the address book, a consent widget will appear. Once the customer consents to billing agreement, you will receive the consent it in the 'change' event.
